name = "flight-stats-scraper"
main = "src/index.ts"
compatibility_date = "2024-03-11"

# KV Namespace for caching flight data
[[kv_namespaces]]
binding = "FLIGHTS_KV"
id = "8379d4f407464879ba783d0e61abe457"

# Cron trigger to refresh flight data every 3 hours
[triggers]
crons = ["0 */3 * * *"]

[vars]
# Add your custom variables here

[env.production]
# Production-specific settings

[env.staging]
# Staging-specific settings

# Enable source maps for debugging
[build]
command = "npm run build"
watch_dir = "src"